import type { SeedLocation } from "./locations-data";

/**
 * Additional seed locations in areas with strong Mapillary street-level coverage.
 * IDs are populated automatically via Mapillary API on startup.
 */
export const extraSeedLocations: SeedLocation[] = [
  // Europe — more coverage
  { lat: 48.1351, lng: 11.5820, country: "Germany", city: "Munich", region: "europe", difficulty: "easy" },
  { lat: 53.5511, lng: 9.9937, country: "Germany", city: "Hamburg", region: "europe", difficulty: "easy" },
  { lat: 50.9375, lng: 6.9603, country: "Germany", city: "Cologne", region: "europe", difficulty: "medium" },
  { lat: 45.4642, lng: 9.1900, country: "Italy", city: "Milan", region: "europe", difficulty: "easy" },
  { lat: 40.8518, lng: 14.2681, country: "Italy", city: "Naples", region: "europe", difficulty: "medium" },
  { lat: 43.2965, lng: 5.3698, country: "France", city: "Marseille", region: "europe", difficulty: "medium" },
  { lat: 45.7640, lng: 4.8357, country: "France", city: "Lyon", region: "europe", difficulty: "medium" },
  { lat: 44.8378, lng: -0.5792, country: "France", city: "Bordeaux", region: "europe", difficulty: "medium" },
  { lat: 53.4808, lng: -2.2426, country: "United Kingdom", city: "Manchester", region: "europe", difficulty: "easy" },
  { lat: 53.4084, lng: -2.9916, country: "United Kingdom", city: "Liverpool", region: "europe", difficulty: "medium" },
  { lat: 55.9533, lng: -3.1883, country: "United Kingdom", city: "Edinburgh", region: "europe", difficulty: "medium" },
  { lat: 51.4545, lng: -2.5879, country: "United Kingdom", city: "Bristol", region: "europe", difficulty: "medium" },
  { lat: 47.3769, lng: 8.5417, country: "Switzerland", city: "Zurich", region: "europe", difficulty: "easy" },
  { lat: 55.6761, lng: 12.5683, country: "Denmark", city: "Copenhagen", region: "europe", difficulty: "easy" },
  { lat: 59.3293, lng: 18.0686, country: "Sweden", city: "Stockholm", region: "europe", difficulty: "easy" },
  { lat: 50.0755, lng: 14.4378, country: "Czech Republic", city: "Prague", region: "europe", difficulty: "easy" },
  { lat: 44.4268, lng: 26.1025, country: "Romania", city: "Bucharest", region: "europe", difficulty: "medium" },
  { lat: 42.6977, lng: 23.3219, country: "Bulgaria", city: "Sofia", region: "europe", difficulty: "medium" },
  { lat: 38.7223, lng: -9.1393, country: "Portugal", city: "Lisbon", region: "europe", difficulty: "easy" },
  { lat: 41.1579, lng: -8.6291, country: "Portugal", city: "Porto", region: "europe", difficulty: "medium" },

  // North America — more US / Canada
  { lat: 39.9526, lng: -75.1652, country: "United States", city: "Philadelphia", region: "north_america", difficulty: "easy" },
  { lat: 33.4484, lng: -112.0740, country: "United States", city: "Phoenix", region: "north_america", difficulty: "easy" },
  { lat: 32.7767, lng: -96.7970, country: "United States", city: "Dallas", region: "north_america", difficulty: "easy" },
  { lat: 39.7392, lng: -104.9903, country: "United States", city: "Denver", region: "north_america", difficulty: "easy" },
  { lat: 33.7490, lng: -84.3880, country: "United States", city: "Atlanta", region: "north_america", difficulty: "easy" },
  { lat: 30.2672, lng: -97.7431, country: "United States", city: "Austin", region: "north_america", difficulty: "medium" },
  { lat: 45.5152, lng: -122.6784, country: "United States", city: "Portland", region: "north_america", difficulty: "medium" },
  { lat: 36.1627, lng: -86.7816, country: "United States", city: "Nashville", region: "north_america", difficulty: "medium" },
  { lat: 32.7157, lng: -117.1611, country: "United States", city: "San Diego", region: "north_america", difficulty: "easy" },
  { lat: 25.7617, lng: -80.1918, country: "United States", city: "Miami", region: "north_america", difficulty: "easy" },
  { lat: 36.1699, lng: -115.1398, country: "United States", city: "Las Vegas", region: "north_america", difficulty: "easy" },
  { lat: 41.4993, lng: -81.6944, country: "United States", city: "Cleveland", region: "north_america", difficulty: "medium" },
  { lat: 39.1031, lng: -84.5120, country: "United States", city: "Cincinnati", region: "north_america", difficulty: "medium" },
  { lat: 42.3314, lng: -83.0458, country: "United States", city: "Detroit", region: "north_america", difficulty: "medium" },
  { lat: 44.9778, lng: -93.2650, country: "United States", city: "Minneapolis", region: "north_america", difficulty: "medium" },
  { lat: 38.6270, lng: -90.1994, country: "United States", city: "St. Louis", region: "north_america", difficulty: "medium" },
  { lat: 39.7684, lng: -86.1581, country: "United States", city: "Indianapolis", region: "north_america", difficulty: "medium" },
  { lat: 35.2271, lng: -80.8431, country: "United States", city: "Charlotte", region: "north_america", difficulty: "medium" },
  { lat: 35.1495, lng: -90.0490, country: "United States", city: "Memphis", region: "north_america", difficulty: "medium" },
  { lat: 29.9511, lng: -90.0715, country: "United States", city: "New Orleans", region: "north_america", difficulty: "medium" },
  { lat: 43.6532, lng: -79.3832, country: "Canada", city: "Toronto", region: "north_america", difficulty: "easy" },
  { lat: 45.5017, lng: -73.5673, country: "Canada", city: "Montreal", region: "north_america", difficulty: "easy" },
  { lat: 53.5461, lng: -113.4938, country: "Canada", city: "Edmonton", region: "north_america", difficulty: "medium" },
  { lat: 49.8951, lng: -97.1384, country: "Canada", city: "Winnipeg", region: "north_america", difficulty: "medium" },
  { lat: 46.8139, lng: -71.2080, country: "Canada", city: "Quebec City", region: "north_america", difficulty: "medium" },
  { lat: 20.5888, lng: -100.3899, country: "Mexico", city: "Queretaro", region: "north_america", difficulty: "medium" },
  { lat: 25.6866, lng: -100.3161, country: "Mexico", city: "Monterrey", region: "north_america", difficulty: "medium" },

  // South America
  { lat: -22.9068, lng: -43.1729, country: "Brazil", city: "Rio de Janeiro", region: "south_america", difficulty: "easy" },
  { lat: -12.9714, lng: -38.5014, country: "Brazil", city: "Salvador", region: "south_america", difficulty: "medium" },
  { lat: -8.0476, lng: -34.8770, country: "Brazil", city: "Recife", region: "south_america", difficulty: "medium" },
  { lat: -3.7172, lng: -38.5433, country: "Brazil", city: "Fortaleza", region: "south_america", difficulty: "medium" },
  { lat: -25.4284, lng: -49.2733, country: "Brazil", city: "Curitiba", region: "south_america", difficulty: "medium" },
  { lat: -30.0346, lng: -51.2177, country: "Brazil", city: "Porto Alegre", region: "south_america", difficulty: "medium" },
  { lat: -19.9167, lng: -43.9345, country: "Brazil", city: "Belo Horizonte", region: "south_america", difficulty: "medium" },
  { lat: -33.4489, lng: -70.6693, country: "Chile", city: "Santiago", region: "south_america", difficulty: "easy" },
  { lat: -33.0472, lng: -71.6127, country: "Chile", city: "Valparaiso", region: "south_america", difficulty: "medium" },
  { lat: -32.8908, lng: -68.8272, country: "Argentina", city: "Mendoza", region: "south_america", difficulty: "medium" },
  { lat: -31.4201, lng: -64.1888, country: "Argentina", city: "Cordoba", region: "south_america", difficulty: "medium" },
  { lat: 6.2442, lng: -75.5812, country: "Colombia", city: "Medellin", region: "south_america", difficulty: "easy" },
  { lat: 3.4516, lng: -76.5320, country: "Colombia", city: "Cali", region: "south_america", difficulty: "medium" },

  // Asia — Japan, India, SE Asia
  { lat: 35.4437, lng: 139.6380, country: "Japan", city: "Yokohama", region: "asia", difficulty: "easy" },
  { lat: 35.1815, lng: 136.9066, country: "Japan", city: "Nagoya", region: "asia", difficulty: "easy" },
  { lat: 43.0621, lng: 141.3544, country: "Japan", city: "Sapporo", region: "asia", difficulty: "medium" },
  { lat: 33.5904, lng: 130.4017, country: "Japan", city: "Fukuoka", region: "asia", difficulty: "medium" },
  { lat: 34.7024, lng: 135.4959, country: "Japan", city: "Osaka", region: "asia", difficulty: "easy" },
  { lat: 28.6139, lng: 77.2090, country: "India", city: "New Delhi", region: "asia", difficulty: "easy" },
  { lat: 13.0827, lng: 80.2707, country: "India", city: "Chennai", region: "asia", difficulty: "medium" },
  { lat: 22.5726, lng: 88.3639, country: "India", city: "Kolkata", region: "asia", difficulty: "medium" },
  { lat: 18.5204, lng: 73.8567, country: "India", city: "Pune", region: "asia", difficulty: "medium" },
  { lat: 17.3850, lng: 78.4867, country: "India", city: "Hyderabad", region: "asia", difficulty: "medium" },
  { lat: 13.7563, lng: 100.5018, country: "Thailand", city: "Bangkok", region: "asia", difficulty: "easy" },
  { lat: 7.8804, lng: 98.3923, country: "Thailand", city: "Phuket", region: "asia", difficulty: "medium" },
  { lat: 3.1390, lng: 101.6869, country: "Malaysia", city: "Kuala Lumpur", region: "asia", difficulty: "easy" },
  { lat: 14.5995, lng: 120.9842, country: "Philippines", city: "Manila", region: "asia", difficulty: "medium" },
  { lat: 10.8231, lng: 106.6297, country: "Vietnam", city: "Ho Chi Minh City", region: "asia", difficulty: "medium" },

  // Africa
  { lat: -33.9249, lng: 18.4241, country: "South Africa", city: "Cape Town", region: "africa", difficulty: "easy" },
  { lat: -26.2041, lng: 28.0473, country: "South Africa", city: "Johannesburg", region: "africa", difficulty: "easy" },
  { lat: -29.8587, lng: 31.0218, country: "South Africa", city: "Durban", region: "africa", difficulty: "medium" },
  { lat: -25.7479, lng: 28.2293, country: "South Africa", city: "Pretoria", region: "africa", difficulty: "medium" },
  { lat: 30.0444, lng: 31.2357, country: "Egypt", city: "Cairo", region: "africa", difficulty: "easy" },
  { lat: 31.6295, lng: -7.9811, country: "Morocco", city: "Marrakech", region: "africa", difficulty: "medium" },
  { lat: 33.5731, lng: -7.5898, country: "Morocco", city: "Casablanca", region: "africa", difficulty: "easy" },
  { lat: -1.2921, lng: 36.8219, country: "Kenya", city: "Nairobi", region: "africa", difficulty: "medium" },

  // Oceania
  { lat: -33.8688, lng: 151.2093, country: "Australia", city: "Sydney", region: "oceania", difficulty: "easy" },
  { lat: -37.8136, lng: 144.9631, country: "Australia", city: "Melbourne", region: "oceania", difficulty: "easy" },
  { lat: -27.4698, lng: 153.0251, country: "Australia", city: "Brisbane", region: "oceania", difficulty: "easy" },
  { lat: -28.0167, lng: 153.4000, country: "Australia", city: "Gold Coast", region: "oceania", difficulty: "medium" },
  { lat: -32.9283, lng: 151.7817, country: "Australia", city: "Newcastle", region: "oceania", difficulty: "medium" },
  { lat: -36.8485, lng: 174.7633, country: "New Zealand", city: "Auckland", region: "oceania", difficulty: "easy" },
  { lat: -41.2865, lng: 174.7762, country: "New Zealand", city: "Wellington", region: "oceania", difficulty: "medium" },
  { lat: -45.0312, lng: 168.6626, country: "New Zealand", city: "Queenstown", region: "oceania", difficulty: "medium" },
];
